/*
    Copyright 2013 NIC Chile Research Labs
    This file is part of TsCrypto.

    TsCrypto is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TsCrypto is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with TsCrypto.  If not, see <http://www.gnu.org/licenses/>.
 */

package cl.niclabs.tscrypto.common.datatypes;

import java.util.UUID;


/**
 * A GroupKey with information common to all the keyshares.
 * Generated by the Dealer class
 * 
 * Reference: "Practical Threshold Signatures",<br>
 * Victor Shoup (sho@zurich.ibm.com), IBM Research Paper RZ3121, 4/30/99<BR>
 * 
 * @author Steve Weis <sweis@mit.edu>
 */
public class KeyMetaInfo extends JsonFormat {
	/** (k,l) Parameters. k out of l shares needed for a signature */
	private int k, l;

	private int keysize;

	/** UUID of this key */
	private String alias;

	/** default digest algorithm */
	private String algorithm = "RSA";
	
	/**
	 * Empty no-args constructor needed by Gson
	 */
	public KeyMetaInfo() {
	}
	
	public KeyMetaInfo(final int k, final int l, final int keysize) {
		this.k = k;
		this.l = l;
		this.keysize = keysize;
		this.alias = UUID.randomUUID().toString();
	}

	/**
	 * Returns the minimum threshold size
	 * 
	 * @return The minimum threshold size for this group 'k'.
	 */
	public int getK() {
		return this.k;
	}

	/**
	 * Returns the group size
	 * 
	 * @return The size of this key's associated group.
	 */
	public int getL() {
		return this.l;
	}


	public int getKeysize() {
		return keysize;
	}

	public String getAlias() {
		return alias;
	}

	public String getAlgorithm() {
		return algorithm;
	}

}