DROP TABLE IF EXISTS TOKEN;
CREATE TABLE TOKEN (TKN_LABEL PRIMARY KEY, TKN_PIN TEXT, TKN_SO_PIN TEXT);

DROP TABLE IF EXISTS CRYPTO_OBJECT;
CREATE TABLE CRYPTO_OBJECT (TKN_LABEL TEXT, CO_HANDLE INTEGER, PRIMARY KEY (TKN_LABEL,  CO_HANDLE));

DROP TABLE IF EXISTS ATTRIBUTE;
CREATE TABLE ATTRIBUTE (TKN_LABEL TEXT,  CO_HANDLE INTEGER, ATT_TYPE INTEGER, ATT_VALUE BLOB, PRIMARY KEY (TKN_LABEL, CO_HANDLE, ATT_TYPE));

-- default token
INSERT INTO TOKEN VALUES ("TCBHSM", "1234", "1234"); 
