/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cl_niclabs_tscrypto_common_algorithms_JniSignWrapper */

#ifndef _Included_cl_niclabs_tscrypto_common_algorithms_JniSignWrapper
#define _Included_cl_niclabs_tscrypto_common_algorithms_JniSignWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cl_niclabs_tscrypto_common_algorithms_JniSignWrapper
 * Method:    mPow
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cl_niclabs_tscrypto_common_algorithms_JniSignWrapper_mPow
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     cl_niclabs_tscrypto_common_algorithms_JniSignWrapper
 * Method:    sign
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_cl_niclabs_tscrypto_common_algorithms_JniSignWrapper_sign
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
